chore(TDI-39964): common jars alignment (#1194)
* chore(TDI-39964): declare jars in parent for aligning versions
* fix(TDI-39964): fix components-api-proptester
* fix(TDI-39964): fix components-api-proptester
* fix(TDI-39964): add compile scope to components-api-proptester
* fix(TDI-39964): remove test scope to junit
* fix(TDI-39964): restore bigquery-runtime dependencies to fix NoClassDefFoundError
* fix(TDI-39964): restore bigquery-integration dependencies to fix NoSuchMethodError
* chore(TDI-39964): rebase on master
* fix(TDI-39964): restore pubsub dependencies to fix NoClassDefFound
* fix(TDI-39964): restore kinesis dependencies (beam)
* fix(TDI-39964): change building order for speeding results (revert after)
* fix(TDI-39964): fix couchbase pom
* chore(TDI-39964): rebase on master
* fix(TDI-39964): disable couchbase temporally
* fix(TDI-39964): fix couchbase build
* chore(TDI-39964): misc adjustments
* fix(TDI-39964): fix simplefileio - components-common
* fix(TDI-39964): fix fileio-integration
* fix(TDI-39964): fix components-api-proptester
* fix(TDI-39964): remove derby versions
* fix(TDI-39964): guava changes
* fix(TDI-39964): rebase on master after jackson bump
* fix(TDI-39964): rebase on master
* fix(TDI-39964): fix rebase
* chore(TDI-39964): bump cxf
* fix(TDI-39964): stabilize mixed tabs and spaces in pom.xml
* fix(TDI-39964): stabilize mixed tabs and spaces in pom.xml (more)
* fix(TDI-39964): normalize commons-io for api-service-rest
* fix(TDI-39964): normalize org.slf4j
* fix(TDI-39964): add com.fasterxml.classmate to parent's pom
* fix(TDI-39964): extract versions to properties for api-service-rest
* fix(TDI-39964): bump some commons-*
* fix(TDI-39964): extract versions to properties for marklogic
* fix(TDI-39964): remove duplicated dependency
* fix(TDI-39964): add missing version to plugin in netsuite-runtime 2014
* fix(TDI-39964): fix clash slf4j and log4j
* fix(TDI-39964): remove duplicated dependency for spring-boot
* fix(TDI-39964): fix rebasing
* fix(TDI-39964): fix duplicated properties
* fix(TDI-39964): add beam.version to parent
* fix(TDI-39964): update google-cloud-bigquery
* fix(TDI-39964): refactor big data libraries
* fix(TDI-39964): move dependencies to BOM
* fix(TDI-39964): add more extra dependencies to BOM
* fix(TDI-39964): extract dependency literal versions
* fix(TDI-39964): fix REST service for all comps
* fix(TDI-39964): remove again duplicated dependencies
* fix(TDI-39964): fix conflicts with master branch
* fix(TDI-39964): correct derby extraArtifact in maven repo
* fix(TDI-39964): extract version from snowflake module
* fix(TDI-39964): change to bundle
* fix(TDI-40311): fix snowflake split